class Quote {
  Quote(this.id, this.body, this.catergory, this.author, {this.isFav = 0});

  final String id;
  final String body;
  final String catergory;
  final String author;
  final int isFav;

  factory Quote.fromMap(Map<String, dynamic> json) => Quote(
        json["id"],
        json["body"],
        json["catergory"],
        json["author"],
        isFav: json['isfav'],
      );

  Map<String, dynamic> toMap() => {
        "id": id,
        "body": body,
        "catergory": catergory,
        "author": author,
        "isfav": isFav
      };
}



List<Quote> quotes = [
  Quote(
      '1',
      'The only person you are destined to become is the person you decide to be.',
      'Fitness',
      'Ralph Waldo Emerson'),
  Quote('2', 'Once you learn to quit, it becomes a habit.', 'Fitness',
      'Vince Lombardi Jr'),
  Quote('3', 'A year from now you may wish you had started today.', 'Fitness',
      'Karen Lamb'),
  Quote(
      '4',
      'Our growing softness, our increasing lack of physical fitness, is a menace to our security.',
      'Fitness',
      'John F. Kennedy'),
  Quote(
      '5',
      'Don’t give up on your dreams, or your dreams will give up on you.',
      'Fitness',
      'John Wooden'),
  Quote(
      '6',
      'The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion.',
      'Fitness',
      'Arnold Schwarzenegger'),
  Quote(
      '7',
      'Most people fail, not because of lack of desire, but, because of lack of commitment.',
      'Fitness',
      'Vince Lombardi'),
  Quote(
      '8',
      'Success usually comes to those who are too busy to be looking for it.',
      'Fitness',
      '-Henry David Thoreau'),
  Quote(
      '9', 'Exercise is labor without weariness.', 'Fitness', 'Samuel Johnson'),
  Quote(
      '10',
      'Some people want it to happen, some wish it would happen, others make it happen.',
      'Fitness',
      'Michael Jordan'),
  Quote('1', "It's not knowing what to do, it's doing what you know.",
      'Productivity', 'Tony Robbins'),
  Quote('2', 'Focus on being productive instead of busy.', 'Productivity',
      'Tim Ferriss'),
  Quote(
      '3',
      "The key is not to prioritize what's on your schedule, but to schedule your priorities.",
      'Productivity',
      'Stephen Covey'),
  Quote(
      '4',
      'Ordinary people think merely of spending time, great people think of using it.',
      'Productivity',
      'Arthur Schopenhauer'),
  Quote('5', ' Your mind is for having ideas, not holding them.',
      'Productivity', ' David Allen '),
  Quote(
      '6',
      "Success is often achieved by those who don't know that failure is inevitable.",
      'Productivity',
      'Coco Chanel'),
  Quote(
      '7',
      "If you don't pay appropriate attention to what has your attention, it will take more of your attention than it deserves.",
      'Productivity',
      'David Allen'),
  Quote('8', 'Action is the foundational key to all success.', 'Productivity',
      'Pablo Picasso'),
  Quote(
      '9',
      'Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort.',
      'Productivity',
      'Paul J. Meyer'),
  Quote('10', 'The best way out is always through.', 'Productivity',
      'Robert Frost'),
  Quote(
      '11',
      "It's not always that we need to do more but rather that we need to focus on less.",
      'Productivity',
      'Nathan W. Morris'),
  Quote(
      '12',
      'Productivity is being able to do things that you were never able to do before.',
      'Productivity',
      'Franz Kafka'),
  Quote('13', 'Life is too complicated not to be orderly.', 'Productivity',
      'Martha Stewart'),
  Quote('14', "You don't need a new plan for next year. You need a commitment.",
      'Productivity', 'Seth Godin'),
  Quote('15', "Until we can manage time, we can manage nothing else ",
      'Productivity', 'Peter Drucker'),
  Quote('16', 'Great acts are made up of small deeds.', 'Productivity',
      'Lao Tzu'),
  Quote('17', "Don't wait. The time will never be just right.", 'Productivity',
      'Napoleon Hill'),
  Quote('18', "Effective performance is preceded by painstaking preparation",
      'Productivity', 'Brian Tracy '),
  Quote('19', 'The way to get started is to quit talking and begin doing.',
      'Productivity', ' Walt Disney'),
  Quote('20', 'Plans are nothing; planning is everything.', 'Productivity',
      'Dwight D. Eisenhower'),
  Quote(
      '1',
      'Even if I spent the whole day with you, I will miss you the second you leave.',
      'love',
      'Khalifatul Masih III'),
  Quote(
      '2',
      'Everyone says you only fall in love once, but that’s not true because every time I see you, I fall in love all over again.',
      'love',
      'Amy Poehler'),
  Quote(
      '3',
      'Dictionary is incomplete because it doesn’t have a word which can describe how much I love you.',
      'love',
      'T.S Eliot'),
  Quote(
      '4',
      'Thank you for stealing my eyes from the crowd and stealing my heart from me.',
      'love',
      'Mark Twain'),
  Quote('5', 'You wanna know who I’m in love with? Read the first word again.',
      'love', 'John Wooden'),
  Quote(
      '6',
      'Every time I look at the keyboard, I see that U and I are always together.',
      'love',
      'Arnold Schwarzenegger'),
  Quote('7', 'Being in love with you makes every morning worth getting up for.',
      'love', 'Vince Lombardi'),
  Quote(
      '8',
      'I fell in love with you not for how you look, just for who you are.',
      'love',
      '-Henry David Thoreau'),
  Quote(
      '9',
      'I wrote your name in the sand, but the waves washed it away. Then I wrote it in the sky, but the wind blew it away. So I wrote it in my heart and that’s where it will stay forever.',
      'love',
      'Samuel Johnson'),
  Quote('11', 'I feel the fragrance of LOVE everywhere when you are near me.',
      'love', 'Khalifatul Masih III'),
  Quote('12', 'Are you a camera? because I smile every time I look at you.',
      'love', 'Amy Poehler'),
  Quote(
      '13',
      'Before I met you I never knew what it was like, to look at someone and smile for no reason.',
      'love',
      'T.S Eliot'),
  Quote(
      '14',
      'You are the girl with the sunshine smile. Your voice is like a ray of hope. You fill my life with all the rainbow colors.',
      'love',
      'Mark Twain'),
  Quote(
      '15',
      'You may hold my hand for a while, but you hold my heart forever.',
      'love',
      'John Wooden'),
  Quote(
      '16',
      'In your smile I see something more beautiful than the moon & stars.',
      'love',
      'Arnold Schwarzenegger'),
  Quote(
      '17',
      'Without you, I’m nothing. With you, I’m something. Together, we’re everything.',
      'love',
      'Vince Lombardi'),
  Quote('18', 'The story of my life is all about you, my love. Love you a lot.',
      'love', '-Henry David Thoreau'),
  Quote(
      '19',
      'I’m in love with every moment I spend with you. I can’t wait to spend the rest of my life with you.',
      'love',
      'Samuel Johnson'),
  Quote(
      '20',
      'When I walk into a room full of people, I always look for you first.',
      'love',
      'Michael Jordan'),
  Quote(
      '21',
      'A friend is someone who knows all about you and still loves you.',
      'love',
      'Elbert Hubbard'),
  Quote(
      '22',
      'It is better to be hated for what you are than to be loved for what you are not.',
      'love',
      'Andre Gide'),
  Quote(
      '23',
      'As he read, I fell in love the way you fall asleep: slowly, and then all at once.',
      'love',
      'John Green'),
  Quote('2', 'Change the world by being yourself.', 'saying', 'Amy Poehler'),
  Quote('3', 'Every moment is a fresh beginning.', 'saying', 'T.S Eliot'),
  Quote('4', 'Never regret anything that made you smile.', 'saying',
      'Mark Twain'),
  Quote('5', 'Die with memories, not dreams.', 'saying', 'John Wooden'),
  Quote('6', 'Aspire to inspire before we expire.', 'saying',
      'Arnold Schwarzenegger'),
  Quote('7', 'Everything you can imagine is real.', 'saying', 'Vince Lombardi'),
  Quote('8', 'Simplicity is the ultimate sophistication.', 'saying',
      '-Henry David Thoreau'),
  Quote('9', 'Whatever you do, do it well.', 'saying', 'Samuel Johnson'),
  Quote('10', 'What we think, we become.', 'saying', 'Michael Jordan'),
  Quote('11', 'All limitations are self-imposed.', 'saying',
      'Khalifatul Masih III'),
  Quote('12', 'Tough times never last but tough people do.', 'saying',
      'Amy Poehler'),
  Quote('13', 'Problems are not stop signs, they are guidelines.', 'saying',
      'T.S Eliot'),
  Quote(
      '14',
      'One day the people that don’t even believe in you will tell everyone how they met you.',
      'saying',
      'Mark Twain'),
  Quote('15', 'If I’m gonna tell a real story, I’m gonna start with my name.',
      'saying', 'John Wooden'),
  Quote('16', 'If you tell the truth you don’t have to remember anything.',
      'saying', 'Arnold Schwarzenegger'),
  Quote('17', 'Have enough courage to start and enough heart to finish.',
      'saying', 'Vince Lombardi'),
  Quote('18', 'Hate comes from intimidation, love comes from appreciation.',
      'saying', '-Henry David Thoreau'),
  Quote('19', 'I could agree with you but then we’d both be wrong.', 'saying',
      'Samuel Johnson'),
  Quote('20', 'Oh, the things you can find, if you don’t stay behind.',
      'saying', 'Michael Jordan'),
  Quote(
      '1',
      'If you’re perhaps tired,unmotivated and just reluctant to do anything and want a few more days of weekend right now then I have something that can help you.',
      'Monday',
      'Bret Contreras'),
  Quote(
      '2',
      'I’ve put together 101 of the most motivational quotes I’ve ever come across to give you a boost of inspiration as you start your Monday and week and maybe help you to find a change in perspective.',
      'Monday',
      'Vidal Sassoon'),
  Quote(
      '3',
      'In the second part I’ll share my own 5 favorite tips that I’ve used the most to overcome my own Monday blues and reluctance and to get my week off to a good and motivated start.',
      'Monday',
      'Greg Plitt'),
  Quote('4', 'Either you run the day or the day runs you.', 'Monday',
      'Mark Twain'),
  Quote(
      '5',
      'Mondays are the start of the work week which offer new beginnings 52 times a year!.',
      'Monday',
      'John Wooden'),
  Quote(
      '6',
      "You've got to get up every morning with determination if you're going to go to bed with satisfaction.",
      'Monday',
      'Arnold Schwarzenegger'),
  Quote(
      '7',
      "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.",
      'Monday',
      'Vince Lombardi'),
  Quote(
      '8',
      'Your Monday morning thoughts set the tone for your whole week. See yourself getting stronger, and living a fulfilling, happier & healthier life.',
      'Monday',
      '-Henry David Thoreau'),
  Quote(
      '9',
      'You don’t have to be great to start, but you have to start to be great.',
      'Monday',
      'Samuel Johnson'),
  Quote(
      '10',
      'Each morning when I open my eyes I say to myself: I, not events, have the power to make me happy or unhappy today. I can choose which it shall be. Yesterday is dead, tomorrow hasn’t arrived yet. I have just one day, today, and I’m going to be happy in it.',
      'Monday',
      'Michael Jordan'),
  Quote(
      '11',
      'Life is full of beauty. Notice it. Notice the bumble bee, the small child, and the smiling faces. Smell the rain, and feel the wind. Live your life to the fullest potential, and fight for your dreams.',
      'Monday',
      'Khalifatul Masih III'),
  Quote(
      '12',
      'When you start to do the things that you truly love, it wouldn’t matter whether it is Monday or Friday; you would be so excited to wake up each morning to work on your passions.',
      'Monday',
      'Amy Poehler'),
  Quote(
      '13',
      'A ship is always safe at shore but that is not what it’s built for.',
      'Monday',
      'T.S Eliot'),
  Quote('14', "Stress is caused by being ‘here' but wanting to be ‘there.",
      'Monday', 'Mark Twain'),
  Quote(
      '15',
      'People rarely succeed unless they have fun in what they are doing.',
      'Monday',
      'John Wooden'),
  Quote('16', 'Your attitude, not your aptitude, will determine your altitude.',
      'Monday', 'Arnold Schwarzenegger'),
  Quote('17', 'You may have to fight a battle more than once to win it.',
      'Monday', 'Vince Lombardi'),
  Quote(
      '19',
      'Try not to become a person of success, but rather try to become a person of value.',
      'Monday',
      'Samuel Johnson'),
  Quote(
      '20',
      'Morning is an important time of day, because how you spend your morning can often tell you what kind of day you are going to have.',
      'Monday',
      'Michael Jordan'),
  Quote('1', 'The purpose of our lives is to be happy.', 'life',
      'Bret Contreras'),
  Quote('2', 'Life is what happens when you’re busy making other plans.',
      'life', 'Vidal Sassoon'),
  Quote('3', 'Get busy living or get busy dying.', 'life', 'Greg Plitt'),
  Quote('4', 'You only live once, but if you do it right, once is enough.',
      'life', 'Mark Twain'),
  Quote(
      '5',
      'Many of life’s failures are people who did not realize how close they were to success when they gave up.',
      'life',
      'John Wooden'),
  Quote(
      '6',
      'If you want to live a happy life, tie it to a goal, not to people or things.',
      'life',
      'Arnold Schwarzenegger'),
  Quote(
      '7',
      'Never let the fear of striking out keep you from playing the game.',
      'life',
      'Vince Lombardi'),
  Quote(
      '8',
      'Money and success don’t change people; they merely amplify what is already there.',
      'life',
      '-Henry David Thoreau'),
  Quote(
      '9',
      'Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma – which is living with the results of other people’s thinking.',
      'life',
      'Samuel Johnson'),
  Quote('10', 'Not how long, but how well you have lived is the main thing.',
      'life', 'Michael Jordan'),
  Quote(
      '11',
      'If life were predictable it would cease to be life, and be without flavor.',
      'life',
      'Khalifatul Masih III'),
  Quote(
      '12',
      'The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.',
      'life',
      'Amy Poehler'),
  Quote('13', 'In order to write about life first you must live it.', 'life',
      'T.S Eliot'),
  Quote(
      '14',
      'The big lesson in life, baby, is never be scared of anyone or anything.',
      'life',
      'Mark Twain'),
  Quote(
      '15',
      'Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth.',
      'life',
      'John Wooden'),
  Quote(
      '16',
      'Curiosity about life in all of its aspects, I think, is still the secret of great creative people.',
      'life',
      'Arnold Schwarzenegger'),
  Quote(
      '17',
      'Life is not a problem to be solved, but a reality to be experienced.',
      'life',
      'Vince Lombardi'),
  Quote('18', 'The unexamined life is not worth living.', 'life',
      '-Henry David Thoreau'),
  Quote('19', 'Turn your wounds into wisdom.', 'life', 'Samuel Johnson'),
  Quote(
      '20',
      'The way I see it, if you want the rainbow, you gotta put up with the rains.',
      'life',
      'Michael Jordan'),
  Quote('2', 'Nothing is impossible. The word itself says ‘I’m possible!.',
      'Inspiration', 'Alexander the Great'),
  Quote('3', 'There is nothing impossible to they who will try.', 'Inspiration',
      'Michael Altshuler'),
  Quote('4', 'The bad news is time flies. The good news is you’re the pilot.',
      'Inspiration', 'Mark Twain'),
  Quote(
      '5',
      'Life has got all those twists and turns. You’ve got to hold on tight and off you go.',
      'Inspiration',
      'John Wooden'),
  Quote(
      '6',
      'Keep your face always toward the sunshine, and shadows will fall behind you.',
      'Inspiration',
      'Arnold Schwarzenegger'),
  Quote(
      '7',
      'Be courageous. Challenge orthodoxy. Stand up for what you believe in. When you are in your rocking chair talking to your grandchildren many years from now, be sure you have a good story to tell.',
      'Inspiration',
      'Vince Lombardi'),
  Quote(
      '8',
      'You make a choice: continue living your life feeling muddled in this abyss of self-misunderstanding, or you find your identity independent of it. You draw your own box.',
      'Inspiration',
      '-Henry David Thoreau'),
  Quote(
      '9',
      'I just want you to know that if you are out there and you are being really hard on yourself right now for something that has happened … it’s normal. That is what is going to happen to you in life. No one gets through unscathed. We are all going to have a few scratches on us. Please be kind to yourselves and stand up for yourself, please.',
      'Inspiration',
      'Samuel Johnson'),
  Quote(
      '10',
      'Success is not final, failure is not fatal: it is the courage to continue that counts.',
      'Inspiration',
      'Michael Jordan'),
  Quote(
      '11',
      'You define your own life. Don’t let other people write your script.',
      'Inspiration',
      'Nicole Kidman'),
  Quote(
      '12',
      'You are never too old to set another goal or to dream a new dream.',
      'Inspiration',
      'Amy Poehler'),
  Quote(
      '13',
      'At the end of the day, whether or not those people are comfortable with how you’re living your life doesn’t matter. What matters is whether you’re comfortable with it.',
      'Inspiration',
      'T.S Eliot'),
  Quote(
      '14',
      'People tell you the world looks a certain way. Parents tell you how to think. Schools tell you how to think. TV. Religion. And then at a certain point, if you’re lucky, you realize you can make up your own mind. Nobody sets the rules but you. You can design your own life.',
      'Inspiration',
      'Mark Twain'),
  Quote(
      '15',
      'For me, becoming isn’t about arriving somewhere or achieving a certain aim. I see it instead as forward motion, a means of evolving, a way to reach continuously toward a better self. The journey doesn’t end.',
      'Inspiration',
      'John Wooden'),
  Quote('16', 'Spread love everywhere you go.', 'Inspiration',
      'Arnold Schwarzenegger'),
  Quote(
      '17',
      'Do not allow people to dim your shine because they are blinded. Tell them to put some sunglasses on.',
      'Inspiration',
      'Vince Lombardi'),
  Quote(
      '18',
      'If you make your internal life a priority, then everything else you need on the outside will be given to you and it will be extremely clear what the next step is.',
      'Inspiration',
      '-Henry David Thoreau'),
  Quote(
      '19',
      'You don’t always need a plan. Sometimes you just need to breathe, trust, let go and see what happens.',
      'Inspiration',
      'Samuel Johnson'),
  Quote(
      '20',
      'You can be everything. You can be the infinite amount of things that people are.',
      'Inspiration',
      'Michael Jordan'),
  Quote(
      '1',
      'The human capacity for burden is like bamboo – far more flexible than you’d ever believe at first glance.',
      'Hard times',
      'Jodi Picoult'),
  Quote(
      '2',
      'I can be changed by what happens to me. But I refuse to be reduced by it.',
      'Hard times',
      'Amy Poehler'),
  Quote(
      '3',
      'On the other side of a storm is the strength that comes from having navigated through it. Raise your sail and begin.',
      'Hard times',
      'T.S Eliot'),
  Quote(
      '4',
      'Although the world is full of suffering, it is also full of the overcoming of it.',
      'Hard times',
      'Mark Twain'),
  Quote('5', 'Turn your wounds into wisdom.', 'Hard times', 'John Wooden'),
  Quote(
      '6',
      'My scars remind me that I did indeed survive my deepest wounds. That in itself is an accomplishment. And they bring to mind something else, too. They remind me that the damage life has inflicted on me has, in many places, left me stronger and more resilient. What hurt me in the past has actually made me better equipped to face the present.',
      'Hard times',
      'Arnold Schwarzenegger'),
  Quote(
      '7',
      'Resilience is accepting your new reality, even if it’s less good than the one you had before. You can fight it, you can do nothing but scream about what you’ve lost, or you can accept that and try to put together something that’s good.',
      'Hard times',
      'Vince Lombardi'),
  Quote('8', 'A good half of the art of living is resilience.', 'Hard times',
      '-Henry David Thoreau'),
  Quote(
      '9',
      'Never say that you can’t do something, or that something seems impossible, or that something can’t be done, no matter how discouraging or harrowing it may be; human beings are limited only by what we allow ourselves to be limited by: our own minds. We are each the masters of our own reality; when we become self-aware to this: absolutely anything in the world is possible.',
      'Hard times',
      'Samuel Johnson'),
  Quote(
      '10',
      'It’s your reaction to adversity, not adversity itself that determines how your life’s story will develop.',
      'Hard times',
      'Michael Jordan'),
  Quote(
      '11',
      'Life doesn’t get easier or more forgiving, we get stronger and more resilient.',
      'Hard times',
      'Khalifatul Masih III'),
  Quote(
      '12',
      'We all have battles to fight. And it’s often in those battles that we are most alive: it’s on the frontlines of our lives that we earn wisdom, create joy, forge friendships, discover happiness, find love, and do purposeful work.',
      'Hard times',
      'Amy Poehler'),
  Quote(
      '13',
      'No matter how much falls on us, we keep plowing ahead. That’s the only way to keep the roads clear.',
      'Hard times',
      'T.S Eliot'),
  Quote(
      '14',
      'Resilience is very different than being numb. Resilience means you experience, you feel, you fail, you hurt. You fall. But, you keep going.',
      'Hard times',
      'Mark Twain'),
  Quote(
      '15',
      'The oak fought the wind and was broken, the willow bent when it must and survived.',
      'Hard times',
      'John Wooden'),
  Quote(
      '16',
      'You must bear losses like a soldier, the voice told me, bravely and without complaint, and just when the day seems lost, grab your shield for another stand, another thrust forward. That is the juncture that separates heroes from the merely strong.',
      'Hard times',
      'Arnold Schwarzenegger'),
  Quote(
      '17',
      'Strong people alone know how to organize their suffering so as to bear only the most necessary pain.',
      'Hard times',
      'Vince Lombardi'),
  Quote(
      '18',
      'Some knowledge is too heavy…you cannot bear it…your Father will carry it until you are able.',
      'Hard times',
      '-Henry David Thoreau'),
  Quote(
      '19',
      'Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.',
      'Hard times',
      'Samuel Johnson'),
  Quote(
      '20',
      'It may sound strange, but many champions are made champions by setbacks.',
      'Hard times',
      'Shane Koyczan'),
  Quote(
      '21',
      'No one escapes pain, fear, and suffering. Yet from pain can come wisdom, from fear can come courage, from suffering can come strength – if we have the virtue of resilience.',
      'Hard times',
      'Khalifatul Masih III'),
  Quote(
      '22',
      'I believe in being strong when everything seems to be going wrong… I believe that tomorrow is another day and I believe in miracles.',
      'Hard times',
      'Amy Poehler'),
  Quote(
      '23',
      'The difference between a strong man and a weak one is that the former does not give up after a defeat.',
      'Hard times',
      'T.S Eliot'),
  Quote(
      '24',
      'Hold yourself responsible for a higher standard than anybody else expects of you. Never excuse yourself. Never pity yourself. Be a hard master to yourself-and be lenient to everybody else.',
      'Hard times',
      'Mark Twain'),
  Quote(
      '25',
      'I hope you never fear those mountains in the distance,ever settle for the path of least resistance.',
      'Hard times',
      'John Wooden'),
  Quote(
      '26',
      'Life is very interesting. In the end, some of your greatest pains become your greatest strengths.',
      'Hard times',
      'Arnold Schwarzenegger'),
  Quote('27', 'My barn having burned down, I can now see the moon.',
      'Hard times', 'Vince Lombardi'),
  Quote('28', 'If you’re going through hell, keep going.', 'Hard times',
      '-Henry David Thoreau'),
  Quote('29', 'Enthusiasm is common. Endurance is rare.', 'Hard times',
      'Samuel Johnson'),
  Quote('30', 'Fall seven times, stand up eight.', 'Hard times',
      'Michael Jordan'),
  Quote(
      '31',
      'Listen to the people who love you. Believe that they are worth living for even when you don’t believe it. Seek out the memories depression takes away and project them into the future. Be brave; be strong; take your pills. Exercise because it’s good for you even if every step weighs a thousand pounds. Eat when food itself disgusts you. Reason with yourself when you have lost your reason.',
      'Hard times',
      'Khalifatul Masih III'),
  Quote(
      '32',
      'We are all faced with a series of great opportunities brilliantly disguised as impossible situations.',
      'Hard times',
      'Amy Poehler'),
  Quote('33', 'Resilience is the ability to attack while running away.',
      'Hard times', 'T.S Eliot'),
  Quote('34', 'You may have to fight a battle more than once to win it.',
      'Hard times', 'Mark Twain'),
  Quote(
      '35',
      'Rock bottom became the solid foundation in which I rebuilt my life.',
      'Hard times',
      'John Wooden'),
  Quote('36', 'That which does not kill us makes us stronger.', 'Hard times',
      'Arnold Schwarzenegger'),
  Quote(
      '37',
      'One’s dignity may be assaulted, vandalized and cruelly mocked, but it can never be taken away unless it is surrendered.',
      'Hard times',
      'Vince Lombardi'),
  Quote(
      '38',
      'The harder you fall, the heavier your heart; the heavier your heart, the stronger you climb; the stronger you climb, the higher your pedestal.',
      'Hard times',
      '-Henry David Thoreau'),
  Quote(
      '39',
      'Successful people demonstrate their resilience through their dedication to making progress every day, even if that progress is marginal.',
      'Hard times',
      'Samuel Johnson'),
  Quote(
      '40',
      'Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying ‘I will try again tomorrow.',
      'Hard times',
      'Shane Koyczan'),
  Quote(
      '41',
      'You have power over your mind – not outside events. Realize this, and you will find strength.',
      'Hard times',
      'Khalifatul Masih III'),
  Quote(
      '42',
      'Failure will never overtake me if my determination to succeed is strong enough.',
      'Hard times',
      'Amy Poehler'),
  Quote('43', 'With the new day comes new strength and new thoughts.',
      'Hard times', 'T.S Eliot'),
  Quote(
      '44',
      'Resilience isn’t a single skill. It’s a variety of skills and coping mechanisms.',
      'Hard times',
      'Mark Twain'),
  Quote(
      '45',
      'I love the man that can smile in trouble, that can gather strength from distress, and grow brave by reflection. ’Tis the business of little minds to shrink, but he whose heart is firm, and whose conscience approves his conduct, will pursue his principles unto death.',
      'Hard times',
      'John Wooden'),
  Quote(
      '46',
      'Hard times don’t create heroes. It is during the hard times when the ‘hero’ within us is revealed..',
      'Hard times',
      'Arnold Schwarzenegger'),
  Quote('47', 'What helps you persevere is your resilience and commitment.',
      'Hard times', 'Vince Lombardi'),
  Quote(
      '48',
      'It’s a funny thing about life, once you begin to take note of the things you are grateful for, you begin to lose sight of the things that you lack.',
      'Hard times',
      '-Henry David Thoreau'),
  Quote('49', 'If your heart is broken, make art with the pieces.',
      'Hard times', 'Samuel Johnson'),
  Quote(
      '50',
      'Happiness isn’t something that depends on our surroundings…it’s something we make inside ourselves.',
      'Hard times',
      'Shane Koyczan'),
  Quote(
      '51',
      'Nothing is more beautiful than the smile that has struggled through the tears.',
      'Hard times',
      'Khalifatul Masih III'),
  Quote(
      '52',
      'Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.',
      'Hard times',
      'Amy Poehler'),
  Quote(
      '53',
      'Hard times may have held you down, but they will not last forever. When all is said and done, you will be increased.',
      'Hard times',
      'T.S Eliot'),
  Quote(
      '54',
      'The world breaks everyone, and afterward, some are strong at the broken places.',
      'Hard times',
      'Mark Twain'),
  Quote(
      '55',
      'It is really wonderful how much resilience there is in human nature. Let any obstructing cause, no matter what, be removed in any way, even by death, and we fly back to first principles of hope and enjoyment.',
      'Hard times',
      'John Wooden'),
  Quote(
      '56',
      'Hard times are sometimes blessings in disguise. We do have to suffer but in the end it makes us strong, better and wise.',
      'Hard times',
      'Arnold Schwarzenegger'),
  Quote(
      '57',
      'Persistence and resilience only come from having been given the chance to work through difficult problems.',
      'Hard times',
      'Vince Lombardi'),
  Quote(
      '58',
      'Difficulties are meant to rouse, not discourage. The human spirit is to grow strong by conflict.',
      'Hard times',
      '-Henry David Thoreau'),
  Quote(
      '59',
      'I have no regrets in my life. I think that everything happens to you for a reason. The hard times that you go through build character, making you a much stronger person.',
      'Hard times',
      'Samuel Johnson'),
  Quote(
      '60',
      'There is meaning in every journey that is unknown to the traveler.',
      'Hard times',
      'Shane Koyczan'),
  Quote(
      '61',
      'Do not judge me by my success, judge me by how many times I fell down and got back up again.',
      'Hard times',
      'Khalifatul Masih III'),
  Quote('62', 'Hard times arouse an instinctive desire for authenticity.',
      'Hard times', 'Amy Poehler'),
  Quote(
      '63',
      'There is a saying in Tibetan, ‘Tragedy should be utilized as a source of strength.’ No matter what sort of difficulties, how painful experience is, if we lose our hope, that’s our real disaster.',
      'Hard times',
      'T.S Eliot'),
  Quote(
      '64',
      'No matter how bleak or menacing a situation may appear, it does not entirely own us. It can’t take away our freedom to respond, our power to take action.',
      'Hard times',
      'Mark Twain'),
  Quote(
      '65',
      'You never know how strong you are, until being strong is your only choice.',
      'Hard times',
      'John Wooden'),
  Quote(
      '66',
      'Anyone can give up; it is the easiest thing in the world to do. But to hold it together when everyone would expect you to fall apart, now that is true strength.',
      'Hard times',
      'Arnold Schwarzenegger'),
  Quote(
      '67',
      'Like tiny seeds with potent power to push through tough ground and become mighty trees, we hold innate reserves of unimaginable strength. We are resilient.',
      'Hard times',
      'Vince Lombardi'),
  Quote(
      '68',
      'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.',
      'Hard times',
      '-Henry David Thoreau'),
  Quote(
      '69',
      'And one has to understand that braveness is not the absence of fear but rather the strength to keep on going forward despite the fear.',
      'Hard times',
      'Samuel Johnson'),
  Quote(
      '70',
      'She stood in the storm and when the wind did not blow her way, she adjusted her sails.',
      'Hard times',
      'Michael Jordan'),
  Quote(
      '71',
      'Courage is the most important of all the virtues because without courage, you can’t practice any other virtue consistently.',
      'Hard times',
      'Khalifatul Masih III'),
  Quote(
      '72',
      'All the adversity I’ve had in my life, all my troubles and obstacles, have strengthened me…. You may not realize it when it happens, but a kick in the teeth may be the best thing in the world for you.',
      'Hard times',
      'Amy Poehler'),
  Quote(
      '73',
      'He who believes is strong; he who doubts is weak. Strong convictions precede great actions.',
      'Hard times',
      'T.S Eliot'),
  Quote(
      '74',
      'Our greatest glory is not in never falling, but in rising every time we fall.',
      'Hard times',
      'Mark Twain'),
  Quote(
      '75',
      'Hard times build determination and inner strength. Through them we can also come to appreciate the uselessness of anger.',
      'Hard times',
      'John Wooden'),
  Quote('76', 'Be patient and tough; someday this pain will be useful to you.',
      'Hard times', 'Arnold Schwarzenegger'),
  Quote('77', 'Only those who dare to fail greatly, can ever achieve greatly.',
      'Hard times', 'Vince Lombardi'),
  Quote(
      '78',
      'Make up your mind that no matter what comes your way, no matter how difficult, no matter how unfair, you will do more than simply survive. You will thrive in spite of it.',
      'Hard times',
      '-Henry David Thoreau'),
  Quote(
      '79',
      'A hero is an ordinary individual who finds the strength to persevere and endure in spite of overwhelming obstacles.',
      'Hard times',
      'Samuel Johnson'),
  Quote('80', 'Grief and resilience live together.', 'Hard times',
      'Shane Koyczan'),
  Quote(
      '81',
      'We are not a product of what has happened to us in our past. We have the power of choice.',
      'Hard times',
      'Khalifatul Masih III'),
  Quote(
      '82',
      'When we learn how to become resilient, we learn how to embrace the beautifully broad spectrum of the human experience.',
      'Hard times',
      'Amy Poehler'),
  Quote(
      '83',
      'When you go through something, like, you learn to appreciate little things – the birds, trees, flowers.',
      'Hard times',
      'T.S Eliot'),
  Quote(
      '84',
      'We do not have to become heroes overnight. Just a step at a time, meeting each thing that comes up, seeing it is not as dreadful as it appeared, discovering we have the strength to stare it down.',
      'Hard times',
      'Mark Twain'),
  Quote(
      '85',
      'Resilience is based on compassion for ourselves as well as compassion for others.',
      'Hard times',
      'John Wooden'),
  Quote(
      '86',
      'Worry does not empty tomorrow of its sorrow. It empties today of its strength.',
      'Hard times',
      'Arnold Schwarzenegger'),
  Quote(
      '87',
      'Every adversity, every failure, and every heartache, carries with it the seed of an equivalent or greater benefit.',
      'Hard times',
      'Vince Lombardi'),
  Quote(
      '88',
      'Confidence, courage and determined spirit are vital for surviving hard times.',
      'Hard times',
      '-Henry David Thoreau'),
  Quote(
      '89',
      'Difficult times have helped me to understand better than before, how infinitely rich and beautiful life is in every way, and that so many things that one goes worrying about are of no importance whatsoever.',
      'Hard times',
      'Samuel Johnson'),
  Quote(
      '90',
      'Hope is the thing with feathers that perches in the soul – and sings the tunes without the words – and never stops at all.',
      'Hard times',
      'Michael Jordan'),
  Quote(
      '91',
      'When things are bad, we take comfort in the thought that they could always get worse. And when they are, we find hope in the thought that things are so bad they have to get better.',
      'Hard times',
      'Khalifatul Masih III'),
  Quote(
      '92',
      'We must accept finite disappointment, but never lose infinite hope.',
      'Hard times',
      'Amy Poehler'),
  Quote(
      '93',
      'The gem cannot be polished without friction, nor man perfected without trials.',
      'Hard times',
      'T.S Eliot'),
  Quote(
      '94',
      'Worry never robs tomorrow of its sorrow, it only saps today of its joy.',
      'Hard times',
      'Mark Twain'),
  Quote(
      '95',
      'And hard times are good in their own way, too. Because the only way you can achieve true happiness is if you experience true sadness as well. It’s all about light and shade. Balance.',
      'Hard times',
      'John Wooden'),
  Quote('96', 'In the middle of difficulty lies opportunity.', 'Hard times',
      'Arnold Schwarzenegger'),
  Quote(
      '97',
      'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.',
      'Hard times',
      'Vince Lombardi'),
  Quote(
      '98',
      'Going through challenging things can teach you a lot, and they also make you appreciate the times that aren’t so challenging.',
      'Hard times',
      '-Henry David Thoreau'),
  Quote(
      '99',
      'You may not always have a comfortable life and you will not always be able to solve all of the world’s problems at once but don’t ever underestimate the importance you can have because history has shown us that courage can be contagious and hope can take on a life of its own.',
      'Hard times',
      'Samuel Johnson'),
  Quote(
      '1',
      'You Can Never Cross The Ocean Unless You Have The Courage To Lose Sight Of The Shore.',
      'future',
      'Bret Contreras'),
  Quote(
      '2',
      'If You Want Something You Never Had, You Have To Do Something You’ve Never Done.',
      'future',
      'Vidal Sassoon'),
  Quote('3', 'The Distance Between Your Dreams And Reality Is Call Action.',
      'future', 'Greg Plitt'),
  Quote(
      '4',
      'Stop Waiting For Friday, For Summer, For Someone To Fall In Love With You, For Life. Happiness Is Achieved When You Stop Waiting For It And Make The Most Of The Moment You Are In Now.',
      'future',
      'Mark Twain'),
  Quote('5', 'Nobody Is Too Busy, It’s Just A Matter Of Priorities.', 'future',
      'John Wooden'),
  Quote('6', 'Do What You Have To Do Until You Can Do What You Want To Do.',
      'future', 'Arnold Schwarzenegger'),
  Quote(
      '7',
      ' Ask Yourself If What You’re Doing Today Is Getting You Closer To Where You Want To Be Tomorrow.',
      'future',
      'Vince Lombardi'),
  Quote('8', 'To Live Will Be An Awfully Big Adventure.', 'future',
      '-Henry David Thoreau'),
  Quote('9', 'I Want To See The World. Follow A Map To Its Edges.', 'future',
      'Samuel Johnson'),
  Quote('10', 'It Is Never Too Late To Be What You Might Have Been.', 'future',
      'Michael Jordan'),
  Quote('11', 'Don’t Wait. Life Goes Faster Than You Think.', 'future',
      'Khalifatul Masih III'),
  Quote('12', 'You’re Never Too Young To Dream BIG!.', 'future', 'Amy Poehler'),
  Quote('13', 'It Feels Good To Be Lost In The Right Direction.', 'future',
      'T.S Eliot'),
  Quote('14', 'If You Haven’t Found It Yet, Keep Looking.', 'future',
      'Mark Twain'),
  Quote('15', 'Don’t Call It A Dream Call It A Plan.', 'future', 'John Wooden'),
  Quote('16', 'Don’t Tell People Your Dream. Show Them.', 'future',
      'Arnold Schwarzenegger'),
  Quote(
      '17',
      'If You Don’t Know Where You Want To Go, Then It Doesn’t Matter Which Path You Take.',
      'future',
      'Vince Lombardi'),
  Quote(
      '18',
      'I Would Rather Regret The Things I Have Done Than The Things I Have Not.',
      'future',
      '-Henry David Thoreau'),
  Quote(
      '19',
      'You Attract What You Are, Not What You Want If You Want Great, Then Be Great.',
      'future',
      'Samuel Johnson'),
  Quote(
      '20',
      'Life Is Not Measured By The Number Of Breaths We Take, But By The Moments That Take Our Breath Away.',
      'future',
      'Michael Jordan'),
  Quote(
      '1',
      'I hope your special day will bring you lots of happiness, love, and fun. You deserve them a lot. Enjoy!.',
      'birthday',
      'Khalifatul Masih III'),
  Quote(
      '2',
      'All things are sweet and bright. May you have a lovely birthday Night.',
      'birthday',
      'Amy Poehler'),
  Quote('3', 'Don’t ever change! Stay as amazing as you are, my friend.',
      'birthday', 'T.S Eliot'),
  Quote(
      '4',
      'Let’s light the candles and celebrate this special day of your life. Happy birthday.',
      'birthday',
      'Mark Twain'),
  Quote(
      '5',
      'Here’s to the sweetest and loveliest person I know. Happy birthday!.',
      'birthday',
      'John Wooden'),
  Quote(
      '6',
      'Happy birthday to my best friend, the one I care about the most!.',
      'birthday',
      'Arnold Schwarzenegger'),
  Quote(
      '7',
      'Wherever your feet may take, whatever endeavor you lay hands on. It will always be successful. Happy birthday.',
      'birthday',
      'Vince Lombardi'),
  Quote(
      '8',
      'May this special day bring you endless joy and tons of precious memories!.',
      'birthday',
      '-Henry David Thoreau'),
  Quote(
      '9',
      'You are very special and that’s why you need to float with lots of smiles on your lovely face. Happy birthday.',
      'birthday',
      'Khalifatul Masih III'),
  Quote(
      '10',
      'It’s as simple as ABC; today makes more sense because of you, Happy birthday.',
      'birthday',
      'Amy Poehler'),
  Quote(
      '11',
      'Let your all the dreams to be on fire and light your birthday candles with that. Have a gorgeous birthday.',
      'birthday',
      'Khalifatul Masih III'),
  Quote(
      '12',
      'May you continue to improve as a person with each passing year. Wishing you a very happy birthday.',
      'birthday',
      'Amy Poehler'),
  Quote(
      '13',
      'Today is the birthday of the person who is spreading joy and positivity all around. May your birthday and your life be as wonderful as you are!.',
      'birthday',
      'T.S Eliot'),
  Quote(
      '14',
      'Happy birthday! Here’s to a bright, healthy and exciting future!.',
      'birthday',
      'Mark Twain'),
  Quote('15', 'The joy is in the air because your special day is here!.',
      'birthday', 'John Wooden'),
  Quote(
      '16',
      'Wishing my friend a very happy birthday and you don’t need to speak it out loud that I’m your best friend too. Love you, dear.',
      'birthday',
      'Arnold Schwarzenegger'),
  Quote(
      '17',
      'Thanks for being a wonderful son to me. I am so fortunate to have a fantastic son like you.',
      'birthday',
      'Vince Lombardi'),
  Quote(
      '18',
      'The years we shared while growing up are like treasures to me. I can remember our every moment of laughter. Happy Birthday, my dear friend.',
      'birthday',
      '-Henry David Thoreau'),
  Quote(
      '19',
      'Your birthday only comes once a year, so make sure this is the most memorable one ever and have a colorful day.',
      'birthday',
      'Samuel Johnson'),
  Quote(
      '20',
      'I gt a feeling that you’ll look really good when you get older. So don’t feel bad about how you look now. Happy birthday my friend!.',
      'birthday',
      'Michael Jordan'),
  Quote(
      '1',
      'Love yourself first, and everything else falls in line. You really have to love yourself to get anything done in this world.',
      'Self-Esteem',
      ' Lucille Ball'),
  Quote('2', 'Talk to yourself like someone you love.', 'Self-Esteem',
      ' Brene Brown '),
  Quote('3', 'To fall in love with yourself is the first secret to happiness..',
      'Self-Esteem', ' Robert Morely '),
  Quote(
      '4',
      'Love yourself. Be clear on how you want to be treated. Know your worth. Always.',
      'Self-Esteem',
      ' Maryam Hasnaa'),
  Quote('5', 'How you love yourself is how you teach others to love you.',
      'Self-Esteem', ' Rupi Kaur '),
  Quote('6', 'Fashion is my way to express how much I love myself.',
      'Self-Esteem', 'Laura Brunereau'),
  Quote(
      '7',
      'If you are always trying to be normal, you will never know how amazing you can be.',
      'Self-Esteem',
      ' Dr. Maya Angelou'),
  Quote('8', 'If you have the ability to love, love yourself first.',
      'Self-Esteem', 'Charles Bukowski'),
  Quote('9', 'Seek to be whole, not perfect.', 'Self-Esteem', ' Oprah'),
  Quote(
      '10',
      'True self-care is not bath salts and chocolate cake, it’s making the choice to build a life you don’t need to escape from.',
      'Self-Esteem',
      'Brianna Wiest '),
  Quote(
      '11',
      'When you say ‘yes’ to others make sure you are not saying ‘no’ to yourself.',
      'Self-Esteem',
      ' Paulo Coelho'),
  Quote('12', 'You alone are enough, you have nothing to prove to anybody.',
      'Self-Esteem', ' Dr. Maya Angelou'),
  Quote(
      '13',
      'I am somebody. I am me. I like being me. And I need nobody to make me somebody.',
      'Self-Esteem',
      ' Louis L’Amour'),
  Quote(
      '14',
      'The more you praise and celebrate your life, the more there is in life to celebrate.',
      'Self-Esteem',
      ' Oprah Winfrey'),
  Quote('15', 'Do things that make you feel good: mind, body, and soul.',
      'Self-Esteem', ' Robyn Conley Downs'),
  Quote(
      '16',
      'I wish I could make everyone understand how important this statement is: go where you are wanted.',
      'Self-Esteem',
      ' S. McNutt'),
  Quote('17', 'She remembered who she was and the game changed.', 'Self-Esteem',
      ' Lalah Deliah'),
  Quote('18', 'I love the person I’ve become because I fought to become her.',
      'Self-Esteem', ' Kaci Diane'),
  Quote(
      '19',
      'Breathe darling, this is just a chapter. It’s not your whole story.',
      'Self-Esteem',
      ' S.C. Laurie'),
  Quote('1', "It's not knowing what to do, it's doing what you know.",
      'Productivity', 'Tony Robbins'),
  Quote('2', 'Focus on being productive instead of busy.', 'Productivity',
      'Tim Ferriss'),
  Quote(
      '3',
      "The key is not to prioritize what's on your schedule, but to schedule your priorities.",
      'Productivity',
      'Stephen Covey'),
  Quote(
      '4',
      'Ordinary people think merely of spending time, great people think of using it.',
      'Productivity',
      'Arthur Schopenhauer'),
  Quote('5', ' Your mind is for having ideas, not holding them.',
      'Productivity', ' David Allen '),
  Quote(
      '6',
      "Success is often achieved by those who don't know that failure is inevitable.",
      'Productivity',
      'Coco Chanel'),
  Quote(
      '7',
      "If you don't pay appropriate attention to what has your attention, it will take more of your attention than it deserves.",
      'Productivity',
      'David Allen'),
  Quote('8', 'Action is the foundational key to all success.', 'Productivity',
      'Pablo Picasso'),
  Quote(
      '9',
      'Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort.',
      'Productivity',
      'Paul J. Meyer'),
  Quote('10', 'The best way out is always through.', 'Productivity',
      'Robert Frost'),
  Quote(
      '11',
      "It's not always that we need to do more but rather that we need to focus on less.",
      'Productivity',
      'Nathan W. Morris'),
  Quote(
      '12',
      'Productivity is being able to do things that you were never able to do before.',
      'Productivity',
      'Franz Kafka'),
  Quote('13', 'Life is too complicated not to be orderly.', 'Productivity',
      'Martha Stewart'),
  Quote('14', "You don't need a new plan for next year. You need a commitment.",
      'Productivity', 'Seth Godin'),
  Quote('15', "Until we can manage time, we can manage nothing else ",
      'Productivity', 'Peter Drucker'),
  Quote('16', "Great acts are made up of small deeds.", 'Productivity',
      'Lao Tzu'),
  Quote('17', "Don't wait. The time will never be just right.", 'Productivity',
      'Napoleon Hill'),
  Quote('18', "Effective performance is preceded by painstaking preparation ",
      'Productivity', 'Brian Tracy '),
  Quote('19', 'The way to get started is to quit talking and begin doing.',
      'Productivity', ' Walt Disney'),
  Quote('20', 'Plans are nothing; planning is everything.', 'Productivity',
      'Dwight D. Eisenhower'),
  Quote('1', "I like the night. Without the dark, we'd never see the stars.",
      'Night', 'Stephenie Meyer'),
  Quote(
      '2',
      'Those who dream by day are cognizant of many things which escape those who dream only by night.',
      'Night',
      'Edgar Allan Poe'),
  Quote('3', 'I have loved the stars too fondly to be fearful of the night.',
      'Night', 'Sarah Williams'),
  Quote('4', 'How did it get so late so soon?', 'Night', 'Dr Seuss'),
  Quote(
      '5',
      "The darker the night, the brighter the stars,The deeper the grief, the closer is God!",
      'Night',
      'Fyodor Dostoevsky'),
  Quote(
      '6',
      'Each night, when I go to sleep, I die. And the next morning, when I wake up, I am reborn.',
      'Night',
      'Mahatma Gandhi'),
  Quote('7', 'What hath night to do with sleep?', 'Night', 'John Milton'),
  Quote(
      '8',
      'The night is the hardest time to be alive and 4am knows all my secrets.',
      'Night',
      'Poppy Z. Brite'),
  Quote(
      '9',
      "This is night, Diddykins. That's what we call it when it goes all dark like this.",
      'Night',
      'J.K. Rowling'),
  Quote('10', "Melancholy were the sounds on a winter's night.", 'Night',
      'Virginia Woolf'),
  Quote(
      '11',
      'The longest way must have its close - the gloomiest night will wear on to a morning.',
      'Night',
      'Harriet Beecher Stowe'),
  Quote(
      '12',
      'I love the silent hour of night,For blissful dreams may then arise,Revealing to my charmed sight What may not bless my waking eyes.',
      'Night',
      'Anne Bronte'),
  Quote(
      '13',
      'She wanted none of those days to end, and it was always with disappointment that she watched the darkness stride forward.',
      'Night',
      'Markus Zusak'),
  Quote(
      '14',
      'Some nights are made for torture, or reflection, or the savoring of loneliness.',
      'Night',
      'Poppy Z.Brite'),
  Quote(
      '15',
      'It was the possibility of darkness that made the day seem so bright.',
      'Night',
      'Stephen King'),
  Quote(
      '16',
      'The sky grew darker, painted blue on blue, one stroke at a time, into deeper and deeper shades of night.',
      'Night',
      'Haruki Murakami'),
  Quote(
      '17',
      'If the stars should appear one night in a thousand years, how would men believe and adore; and preserve for many generations the remembrance of the city of God which had been shown! But every night come out these envoys of beauty, and light the universe with their admonishing smile.',
      'Night',
      'Ralph Waldo Emerson'),
  Quote('18', 'Night Triumphant- and the Stars Eternal.', 'Night',
      'Sarah J. Maas'),
  Quote(
      '19',
      "That's the advantage of insomnia. People who go to be early always complain that the night is too short, but for those of us who stay up all night, it can feel as long as a lifetime. You get a lot done",
      'Night',
      'Banana Yoshimoto'),
  Quote(
      '20',
      'May I kiss you then? On this miserable paper? I might as well open the window and kiss the night air.',
      'Night',
      'Franz Kafka'),
  Quote(
      '1',
      'The gladdest moment in human life is a departure into unknown lands.',
      'Travel',
      'Sir Richard Burton'),
  Quote('2', 'Be fearless in the pursuit of what sets your soul on fire.',
      'Travel', ' Jennifer Lee'),
  Quote(
      '3',
      ' Travel makes one modest. You see what a tiny place you occupy in the world.',
      'Travel',
      ' Gustav Flaubert'),
  Quote(
      '4',
      ' Traveling – it leaves you speechless, then turns you into a storyteller.',
      'Travel',
      ' Ibn Battuta'),
  Quote(
      '5',
      ' Better to see something once than hear about it a thousand times',
      'Travel',
      ' Tailor Davis'),
  Quote('6', ' Adventure may hurt you but monotony will kill you.', 'Travel',
      'Ghaniya Dewi Arassyi'),
  Quote('7', ' Don’t listen to what they say. Go see.', 'Travel', 'Anonymous'),
  Quote('8', ' All you need to know is that it’s possible.', 'Travel', ' Wolf'),
  Quote('9', ' To Travel is to Live', 'Travel', ' Hans Christian Andersen'),
  Quote(
      '10',
      ' The life you have led doesn’t need to be the only life you have.',
      'Travel',
      ' Anna Quindlen'),
  Quote(
      '11',
      ' The most beautiful in the world is, of course, the world itself.',
      'Travel',
      ' Wallace Stevens'),
  Quote('12', ' Work, Travel, Save, Repeat', 'Travel', ' Alberto'),
  Quote('13', ' The journey not the arrival matters.', 'Travel', ' T.S. Eliot'),
  Quote('14', ' Life is short and the world is wide', 'Travel', ' Simon Raven'),
  Quote('15', ' Dare to live the life you’ve always wanted.', 'Travel',
      'Anonymous'),
  Quote('16', ' Travel and change of place impart new vigor to the mind.',
      'Travel', ' Seneca'),
  Quote('17', ' He who would travel happily must travel light.', 'Travel',
      ' Antoine de St. Exupery'),
  Quote(
      '18',
      ' And then there is the most dangerous risk of all — the risk of spending your life not doing what you want on the bet you can buy yourself the freedom to do it later.',
      'Travel',
      ' Randy Komisar'),
  Quote(
      '19',
      ' No one realizes how beautiful it is to travel until he comes home and rests his head on his old, familiar pillow.',
      'Travel',
      ' Lin Yutang'),
  Quote(
      '20',
      ' Our battered suitcases were piled on the sidewalk again; we had longer ways to go. But no matter, the road is life.',
      'Travel',
      ' Jack Kerouac'),
  Quote(
      '1',
      'I don’t count my situps. I only start counting once it starts hurting.',
      'Sport',
      'Muhammad Ali'),
  Quote(
      '2',
      'Cancer can take away all my physical abilities. It cannot touch my mind, it cannot touch my heart and it cannot touch my soul. And those three things are going to carry on forever.',
      'Sport',
      'Jimmy Valvano'),
  Quote(
      '3',
      'I’ve failed over and over again in my life. And that is why I succeed.',
      'Sport',
      'Michael Jordan'),
  Quote('4', 'The only way to prove you are a good sport is to lose.', 'Sport',
      'Ernie Banks'),
  Quote(
      '5',
      'There may be people that have more talent than you, but there’s no excuse for anyone to work harder than you do.',
      'Sport',
      'Derek Jeter'),
  Quote('6', 'If you fail to prepare, you’re prepared to fail.', 'Sport',
      'Mark Spitz'),
  Quote('7', 'The road to Easy Street goes through the sewer.', 'Sport',
      'John Madden'),
  Quote(
      '8',
      'Stubbornness usually is considered a negative; but I think that trait has been a positive for me.',
      'Sport',
      'Cal Ripken, Jr.'),
  Quote(
      '9',
      'To uncover your true potential you must first find your own limits and then you have to have the courage to blow past them.',
      'Sport',
      'Picabo Street'),
  Quote(
      '10',
      'Do you know what my favorite part of the game is? The opportunity to play.',
      'Sport',
      'Mike Singletary'),
  Quote(
      '11',
      'Never let your head hang down. Never give up and sit down and grieve. Find another way.',
      'Sport',
      'Satchel Paige'),
  Quote(
      '12',
      'It is not the size of a man but the size of his heart that matters.',
      'Sport',
      'Evander Holyfield'),
  Quote('13', 'You miss 100 percent of the shots you don’t take.', 'Sport',
      'Wayne Gretzky'),
  Quote('14', 'Wisdom is always an overmatch for strength.', 'Sport',
      'Phil Jackson'),
  Quote('15', 'It’s not whether you get knocked down; it’s whether you get up.',
      'Sport', 'Vince Lombardi'),
  Quote('16', 'Hard work beats talent when talent doesn’t work hard.', 'Sport',
      'Tim Notke'),
  Quote(
      '17',
      'Never say never because limits, like fears, are often just an illusion.',
      'Sport',
      'Michael Jordan'),
  Quote(
      '18', 'Good is not good when better is expected.', 'Sport', 'Vin Scully'),
  Quote('19', 'Without self-discipline, success is impossible, period.',
      'Sport', 'Lou Holtz'),
  Quote(
      '20',
      'It’s not the will to win that matters — everyone has that. It’s the will to prepare to win that matters.',
      'Sport',
      'Paul Bear Bryant'),
  Quote(
      '1',
      'Live as if you were to die tomorrow. Learn as if you were to live forever.',
      'Past',
      'Mahatma Gandhi'),
  Quote('2', 'That which does not kill us makes us stronger.', 'Past',
      'Friedrich Nietzsche'),
  Quote(
      '3',
      'Be who you are and say what you feel, because those who mind don’t matter and those who matter don’t mind.',
      'Past',
      'Bernard M. Baruch'),
  Quote(
      '4',
      'We must not allow other people’s limited perceptions to define us.',
      'Past',
      'Virginia Satir'),
  Quote('5', 'Do what you can, with what you have, where you are.', 'Past',
      'Theodore Roosevelt'),
  Quote('6', 'Be yourself; everyone else is already taken.', 'Past',
      'Oscar Wilde'),
  Quote('7', 'This above all: to thine own self be true.', 'Past',
      'William Shakespeare'),
  Quote('8', 'If you cannot do great things, do small things in a great way.',
      'Past', 'Napoleon Hill'),
  Quote('9', 'If opportunity doesn’t knock, build a door.', 'Past',
      'Milton Berle'),
  Quote(
      '10',
      'Wise men speak because they have something to say; fools because they have to say something.',
      'Past',
      'Plato'),
  Quote('11', 'Strive not to be a success, but rather to be of value.', 'Past',
      'Albert Einstein'),
  Quote(
      '12',
      'Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.',
      'Past',
      'Robert Frost'),
  Quote('13', 'Do not let what you cannot do interfere with what you can do.',
      'Past', 'John Wooden'),
  Quote(
      '14',
      'Whenever you find yourself on the side of the majority, it is time to pause and reflect.',
      'Past',
      'Mark Twain'),
  Quote('15', 'I haven’t failed. I’ve just found 10,000 ways that won’t work.',
      'Past', 'Thomas Edison'),
  Quote('16', 'A journey of a thousand leagues begins beneath one’s feet.',
      'Past', 'Lao Tzu'),
  Quote(
      '17',
      'I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.',
      'Past',
      'Maya Angelou'),
  Quote(
      '18', 'Either you run the day, or the day runs you.', 'Past', 'Jim Rohn'),
  Quote('19', 'Life shrinks or expands in proportion to one’s courage.', 'Past',
      'Anais Nin'),
  Quote('20', 'You must be the change you wish to see in the world.', 'Past',
      'Mahatma Gandhi'),
  Quote(
      '1',
      'You can do anything as long as you have the passion, the drive, the focus, and the support..',
      'Passion',
      'Sabrina Bryan'),
  Quote(
      '2',
      'I have to face life with a newly found passion. I must rediscover the irresistible will to learn, to live and to love.',
      'Passion',
      'Andrea Bocelli'),
  Quote(
      '3',
      'If you don’t love what you do, you won’t do it with much conviction or passion.',
      'Passion',
      'Mia Hamm'),
  Quote(
      '4',
      'Follow your own passion—not your parents’, not your teachers’—yours.',
      'Passion',
      'Robert Ballard'),
  Quote(
      '5',
      'If you feel like there’s something out there that you’re supposed to be doing, if you have a passion for it, then stop wishing and just do it.',
      'Passion',
      'Wanda Sykes'),
  Quote(
      '6',
      'There is no passion to be found playing small—in settling for a life that is less than the one you are capable of living.',
      'Passion',
      'Nelson Mandela'),
  Quote(
      '7',
      'Passion is energy. Feel the power that comes from focusing on what excites you.',
      'Passion',
      'Oprah Winfrey'),
  Quote(
      '8',
      'Nothing is as important as passion. No matter what you want to do with your life, be passionate.',
      'Passion',
      'Jon Bon Jovi'),
  Quote(
      '9',
      'A great leader’s courage to fulfill his vision comes from passion, not position.',
      'Passion',
      'John C. Maxwell'),
  Quote('10', 'Passion is the genesis of genius.', 'Passion', 'Tony Robbins'),
  Quote('11', 'I would rather die of passion than of boredom.', 'Passion',
      'Vincent Van Gogh'),
  Quote(
      '12',
      'If you can’t figure out your purpose, figure out your passion. For your passion will lead you right into your purpose.',
      'Passion',
      'Bishop T.D. Jakes'),
  Quote('13', 'Chase your passion, not your pension.', 'Passion',
      'Denis Waitley'),
  Quote(
      '14',
      'Without passion man is a mere latent force and possibility, like the flint which awaits the shock of the iron before it can give forth its spark.',
      'Passion',
      'Henri Frederic Amiel'),
  Quote(
      '15',
      'Only passions, great passions, can elevate the soul to great things.',
      'Passion',
      'Denis Diderot'),
  Quote(
      '16',
      'You have to be burning with an idea, or a problem, or a wrong that you want to right. If you’re not passionate enough from the start, you’ll never stick it out.',
      'Passion',
      'Steve Jobs'),
  Quote('17', 'Chase down your passion like it’s the last bus of the night.',
      'Passion', ' Terri Guillemets'),
  Quote(
      '18',
      'One person with passion is better than forty people merely interested.',
      'Passion',
      ' E. M. Forster'),
  Quote('19', 'You can’t fake passion.', 'Passion', ' Barbara Corcoran '),
  Quote('20', 'If passion drives you, let reason hold the reins.', 'Passion',
      'Benjamin Franklin'),
];
